using System.Text.Json.Serialization;

namespace Automation;

[JsonConverter(typeof(JsonStringEnumConverter))]
internal enum VariableProvenance {
	/// <summary>Freshly generated by the engine at runtime (state, nonce, code_verifier, ...).</summary>
	Generated,

	/// <summary>Recovered by inspecting the original capture (endpoints, or a stale fallback value with a caveat).</summary>
	Discovered,

	/// <summary>Extracted from a live response during this run (e.g. authorization code, hidden form fields).</summary>
	Extracted,

	/// <summary>Supplied directly by the caller via AutomationOptions.</summary>
	CallerSupplied,
}

/// <summary>Per spec, values are never redacted here - consistent with the detector's Auth.Variable.</summary>
internal sealed record ResolvedVariable(
	string Name,
	string Value,
	VariableProvenance Provenance,

	[property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] Auth.VariableCategory? OriginalCategory = null,
	[property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] string? DerivedFromVariableName = null,
	[property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] string? Notes = null
);
