using System.Text.Json.Serialization;

namespace Auth;

/// <summary>
/// How a variable participating in an authentication flow should be treated by a replay engine.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
internal enum VariableCategory {
	/// <summary>Known before the flow starts (e.g. client_id, redirect_uri, scope).</summary>
	Configuration,

	/// <summary>Known before the flow starts, but sensitive (e.g. client_secret).</summary>
	Secret,

	/// <summary>Generated by the client/browser at runtime (e.g. state, nonce, code_verifier).</summary>
	GeneratedPerFlow,

	/// <summary>Returned by the identity provider (e.g. code, access_token, id_token).</summary>
	ServerGenerated,

	/// <summary>Calculated from other variables (e.g. code_challenge from code_verifier).</summary>
	Derived,

	/// <summary>Present but not required to reproduce the flow (e.g. analytics cookies).</summary>
	NonParticipating,
}
